packages:
  - 'packages/*'
publicHoistPattern:
  - "style-inject"
  - "*jest*"
allowBuilds:
  "@swc/core": true
  esbuild: true
  lefthook: true
overrides:
  "react": "npm:react"
  "vite-plugin-pwa>vite": "npm:vite"
minimumReleaseAge: 1440
