packages:
  - 'packages/*'
publicHoistPattern:
  - "style-inject"
  - "*jest*"
allowBuilds:
  "@swc/core": true
  esbuild: true
  lefthook: true
overrides:
  "react": "19"
  "vite-plugin-pwa>vite": "$vite"
