import type { FC, ReactNode } from 'react';

import 'antd/dist/reset.css';

import '@/app/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <html lang="zh">
      <body>{children}</body>
    </html>
  );
};
export default RootLayout;
