name: Pull request check

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  check:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - uses: pnpm/setup@v2
        with:
          cache: false
          install: true
      - run: pnpm run lint
      - run: pnpm run build
